!
! R3 IGP Metric Configuration
! Updated after R1-R4 link failure - 2026-04-08
!
router isis 1
 interface to-R4
  isis metric 15
 !
!
! R2 IGP Metric Configuration  
! Updated after R1-R4 link failure - 2026-04-08
!
router isis 1
 interface to-R5
  isis metric 8
 !
!