! Nokia 7750 SR Configuration
! Device: R3
! Generated: 2026-04-08 13:08:50 UTC
! Incident: R1-R4 link failure response

configure
    router
        isis
            interface to-R4
                metric 15
                exit
            exit
        exit
    exit
    
    router
        interface to-R4
            isis
                metric 15
                exit
            exit
        exit