! R1 Configuration Update - Post R1-R4 Failure
! Generated: 2026-04-08 08:21:38 UTC
! 
interface GigabitEthernet0/0/1
 description to-R2
 ip ospf cost 15
!
interface GigabitEthernet0/0/6  
 description to-R6
 ip ospf cost 8
!