! R2 Configuration Changes - Post R1-R4 Failure Optimization
! Updated: 2026-04-08 08:11 UTC
! Incident: R1-R4 link failure causing traffic redistribution

router isis CORE
 interface GigabitEthernet0/0/0/1
  description to R3
  isis metric 20  ! Changed from 10 to discourage R3-R4 congestion
  !
 interface GigabitEthernet0/0/0/2  
  description to R5
  isis metric 10  ! Unchanged - prefer this path
  !
!