"""
ORCA Notifications — SendGrid + mailto queue for dashboard display
"""
import os, json, urllib.request, urllib.error, urllib.parse, time
from datetime import datetime

VENDOR_TEMPLATES = {
    "cisco": """CISCO TAC — AUTOMATED FAULT REPORT
====================================
Case Priority : {priority} | Date/Time: {timestamp}
Node          : {node} | Platform: Cisco IOS-XR | Location: {location}
Fault Type    : {fault_type} | Severity: {severity}
Description   : {description}
Affected LSPs : {affected_lsps}
Actions Taken : {actions_taken}
Suspected Cause: {suspected_cause}
---
Auto-generated by ORCA · Autonomous Network Operations & Response Agent""",

    "juniper": """JUNIPER NETWORKS — AUTOMATED SUPPORT REQUEST
=============================================
Priority: {priority} | Submitted: {timestamp}
Node: {node} | Platform: Juniper MX | Location: {location}
Fault: {fault_type} | Severity: {severity}
{description}
Affected LSPs: {affected_lsps}
Automated Actions: {actions_taken}
Suspected: {suspected_cause}
---
Auto-generated by ORCA · Autonomous Network Operations & Response Agent""",

    "nokia": """NOKIA NETWORKS — FAULT NOTIFICATION
=====================================
Priority: {priority} | Date: {timestamp}
Node: {node} | Platform: Nokia 7750 SR | Location: {location}
Fault: {fault_type} | Severity: {severity}
{description}
LSPs Affected: {affected_lsps}
Automated Actions: {actions_taken}
Suspected: {suspected_cause}
---
Auto-generated by ORCA · Autonomous Network Operations & Response Agent""",
}

_email_queue: list = []

def get_pending_emails() -> list:
    return list(_email_queue)

def clear_emails():
    _email_queue.clear()

def send_email(to: str, subject: str, body: str, **kwargs) -> dict:
    email_record = {
        "id": f"email-{int(time.time()*1000)}",
        "to": to, "subject": subject, "body": body,
        "timestamp": datetime.utcnow().isoformat(),
        "mailto": f"mailto:{urllib.parse.quote(to)}?subject={urllib.parse.quote(subject)}&body={urllib.parse.quote(body[:1800])}"
    }

    api_key = os.getenv("SENDGRID_API_KEY", "")
    if api_key:
        try:
            from_email = os.getenv("SMTP_USER", "sireenmalik@gmail.com")
            html = f"""<html><body style="background:#0d1117;color:#e6edf3;font-family:monospace;padding:24px;max-width:700px;margin:auto;">
<div style="border-left:4px solid #00b0f0;padding-left:16px;margin-bottom:20px;">
<h2 style="color:#00b0f0;margin:0;">⚡ ORCA</h2>
<p style="color:#8b949e;margin:4px 0 0;font-size:12px;">Autonomous Network Operations & Response Agent</p>
</div>
<pre style="background:#161b22;border:1px solid #30363d;border-radius:6px;padding:16px;font-size:13px;line-height:1.6;white-space:pre-wrap;">{body}</pre>
</body></html>"""
            payload = json.dumps({
                "personalizations": [{"to": [{"email": to}]}],
                "from": {"email": from_email, "name": "ORCA Network Agent"},
                "subject": subject,
                "content": [{"type": "text/plain", "value": body},
                             {"type": "text/html", "value": html}]
            }).encode()
            req = urllib.request.Request(
                "https://api.sendgrid.com/v3/mail/send", data=payload,
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                email_record["sent"] = True
                email_record["message"] = f"Sent via SendGrid (HTTP {resp.status})"
        except Exception as e:
            email_record["sent"] = False
            email_record["message"] = f"SendGrid: {str(e)[:80]}"
    else:
        email_record["sent"] = False
        email_record["message"] = "Ready — click Open in Mail Client"

    # Deduplicate — skip if identical subject sent in last 60 seconds
    now = time.time()
    for existing in _email_queue:
        if existing["subject"] == email_record["subject"]:
            try:
                existing_time = __import__('datetime').datetime.fromisoformat(existing["timestamp"]).timestamp()
                if now - existing_time < 60:
                    return {"success": True, "email_id": existing["id"],
                            "mailto": existing["mailto"], "message": "Deduplicated — same subject sent recently",
                            "to": to, "subject": subject}
            except: pass

    _email_queue.append(email_record)
    return {"success": True, "email_id": email_record["id"],
            "mailto": email_record["mailto"],
            "message": email_record.get("message", "Queued"),
            "to": to, "subject": subject}

def build_tac_email(vendor: str, fault_data: dict) -> str:
    template = VENDOR_TEMPLATES.get(vendor.lower(), VENDOR_TEMPLATES["nokia"])
    defaults = {
        "timestamp": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "priority": "P2", "node": "Unknown", "location": "DC-SFO2 / Rack A3",
        "severity": "Major", "fault_type": "Interface Fault",
        "description": "Network fault detected by ORCA",
        "affected_lsps": "None",
        "actions_taken": "LSPs rerouted autonomously by ORCA",
        "suspected_cause": "Hardware or optics degradation",
    }
    defaults.update(fault_data)
    return template.format(**defaults)
